# Generated by Django 5.0.3 on 2024-03-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
    ]
