# Generated by Django 5.0.3 on 2024-03-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_car_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='description',
            new_name='slogan',
        ),
    ]
